### ISSUE TITLE
Expose HTTP Status Code onRequestEnd

### ISSUE THREAD

**Issue by coryasilva** [atuttle/Taffy#245]
Per conversation with @terryschwabl in the Coldfusion IRC channel; there may be times where we want to know the response header for audit logging.  

@ryanguill pointed out that there are ways around this but calling a function inside of `representationOf(buildResponseAndLogAudit(data))`

_Also just as a reminder @atuttle thought about modifying the caching hook to receive the status code_

**Comment by ryanguill** [comment]
might be worth considering putting everything from taffy's onRequest() _taffyRequest in the request scope directly - there might be all kinds of information in there that someone might want to do something with in the onRequestEnd.

**Comment by atuttle** [comment]
Thanks guys. If I do put everything in the request scope, it will go in as an "undocumented feature" such that its structure and contents may change at any point without warning. Would that be reasonable?

**Comment by ryanguill** [comment]
hmm, thats a good point.  Maybe copy certain things like the headers and status codes in there and just document those?  I can't really see you ever removing information, but possibly wanting to rename it - which you could do with a deprecation cycle though.

**Comment by atuttle** [comment]
Yeah I don't see anything wrong with copying specific datasets into request scope with plans to support them into the future. The response object would be an easy one, that would contain the data, headers, and status code from the resource. Metrics might be another interesting data point.

**Comment by ryanguill** [comment]
there may be performance considerations for copying all of the response data - some responses may be quite large and that operation may take a while plus the memory usage.  Maybe do everything else by default and put the data behind a framework setting feature gate?

**Comment by atuttle** [comment]
I'm not crazy about the idea of adding another config setting. Can you try to benchmark it and see if there is a consistent increase in memory usage or response latency if you were to just copy `_taffyrequest` to request scope at the end of onRequest?

**Comment by ryanguill** [comment]
I wont have time for that for a while - if someone else doesn't do it I will try to pick it up eventually.

**Comment by coryasilva** [comment]
What do you think about adding a configuration that defines which function (if any) Taffy would use to do the copying of `_taffyrequest` to the request scope?  That way the user can just choose his the information pertinent to his application...Admittedly though, this is not very user friendly.  

OR...

Maybe we can think about adding logging more as a framework feature where each resource route may have logging enabled or disabled and optionally differently logging settings.

````java
    component extends="taffy.core.resource" taffy_uri="/forms/{id}" taffy_log="shallow" {
        // Logging can be set to 'shallow' | 'deep' | '{some user defined level}'
        // The existence of this variable sets enables the logging
    }
````

**Comment by atuttle** [comment]
I think logging is an interesting idea, and something we can discuss, but a separate thread. This one seems to be specifically about exposing all of the parts of the response in much the same way that `onTaffyRequest` exposes all of the parts of the request.

**Comment by atuttle** [comment]
#279 should address this once it's in

**Comment by atuttle** [comment]
#279 was merged, closing this as resolved.

**Comment by coryasilva** [comment]
w00t!
