### ISSUE TITLE
Dashboard Bug in cf9

### ISSUE THREAD

**Issue by guillaume-boivin** [atuttle/Taffy#248]
Coldfusion Enterprise version : 9,0,0,251028
Java version : 1.6.0_14  
Taffy version : 3.0.0

In the file dashboard.cfm, the continue statement at line 357 causes a java error.

```js
{
    "STACKTRACE": [
        {
            "RAW_TRACE": "java.lang.VerifyError: (class: cfdashboard2ecfm1149739734, method: _factor7 signature: (Ljavax/servlet/jsp/tagext/Tag;Ljavax/servlet/jsp/JspWriter;)Ljava/lang/Object;) Illegal target of jump or branch",
            "TEMPLATE": "class: cfdashboard2ecfm1149739734, method: _factor7 signature",
            "LINE": -1,
            "TYPE": "CFML",
            "COLUMN": 0
        },
        {
            "RAW_TRACE": "\tat cfapi2ecfc1375100622$funcONREQUESTSTART._factor0(C:\\inetpub\\wwwroot\\Dev\\taffyTest\\taffy\\core\\api.cfc:84)",
            "ID": "CFINCLUDE",
            "TEMPLATE": "C:\\inetpub\\wwwroot\\Dev\\taffyTest\\taffy\\core\\api.cfc",
            "LINE": 84,
            "TYPE": "CFML",
            "COLUMN": 0
        },
        {
            "RAW_TRACE": "\tat cfapi2ecfc1375100622$funcONREQUESTSTART.runFunction(C:\\inetpub\\wwwroot\\Dev\\taffyTest\\taffy\\core\\api.cfc:79)",
            "ID": "CF_API",
            "TEMPLATE": "C:\\inetpub\\wwwroot\\Dev\\taffyTest\\taffy\\core\\api.cfc",
            "LINE": 79,
            "TYPE": "CFML",
            "COLUMN": 0
        },
        {
            "RAW_TRACE": "\tat cfapplication2ecfc666613772$funcONREQUESTSTART.runFunction(C:\\inetpub\\wwwroot\\Dev\\taffyTest\\application.cfc:12)",
            "ID": "CF_UDFMETHOD",
            "TEMPLATE": "C:\\inetpub\\wwwroot\\Dev\\taffyTest\\application.cfc",
            "LINE": 12,
            "TYPE": "CFML",
            "COLUMN": 0
        }
    ],
    "TAGCONTEXT": "class: cfdashboard2ecfm1149739734, method: _factor7 signature [Line -1]",
    "DETAIL": "",
    "ERROR": "(class: cfdashboard2ecfm1149739734, method: _factor7 signature: (Ljavax/servlet/jsp/tagext/Tag;Ljavax/servlet/jsp/JspWriter;)Ljava/lang/Object;) Illegal target of jump or branch"
}
```

**Comment by atuttle** [comment]
This doesn't seem right to me. Your fix in #249 may well resolve the issue, but I believe there is something else wrong. This is pretty vanilla code that's been supported for years and years.

Your Java version is a little outdated. Would you mind updating to a more recent version and trying again? It looks like CF9 is certified on Java 7 update 55. Indeed you'll want to be on 1.7.0_55 or 1.6.0_75 [for security reasons](http://www.oracle.com/technetwork/java/javase/7u55-relnotes-2177812.html), anyway.

**Comment by guillaume-boivin** [comment]
Good point, I'm closing the issue.

**Comment by gensior** [comment]
I'm getting the same thing with this setup:
ColdFusion Server Developer 	9,0,1,274733
Java: 1.7.0_55
Taffy: 3.0.0

@guillaume-boivin 's code seems to fix my situation.

**Comment by atuttle** [comment]
That's pretty weird. I would suggest trying to create a super tiny test case to be able to post a bug report for Adobe. If you can create a code sample that's just 5-10 lines long (or less) that shows the same issue, that sounds like a valid bug report (against CF) to me.

**Comment by gensior** [comment]
Sounds good. I'll link to the bug report when I create it, for reference.
