### ISSUE TITLE
unable to add mixins to resource cfcs

### ISSUE THREAD

**Issue by tvanderlois** [atuttle/Taffy#261]
Attempted cfinclude and extending a commonCFC to inherit methods (specifically a GET method). Taffy does not recognize the methods.

**Comment by atuttle** [comment]
ref: https://groups.google.com/forum/#!topic/taffy-users/mh00_BzsIgU

**Comment by atuttle** [comment]
@tvanderlois Just in case I have trouble reproducing, can you let me know what version of CF you're on, and what platform you're running on?

**Comment by atuttle** [comment]
Unfortunately, I just don't think this is something ColdFusion will allow us to do! Taffy uses `getMetadata()` to get the list of functions within each object (and additional metadata about those functions), which doesn't see the result of the `<cfinclude>`, even though those functions _are_ available at runtime.

I also tried `getComponentMetadata()`, but it suffers from the same problem. There's just no way to get the necessary information from a component using mixins, even after it's been instantiated!

So, I **hate** this but it's true: We just can't support mixins (if the functions are defined in the mixins). You _have_ to use inheritance to share functions between resources. You _could_ use mixins for function contents, as in:

```
<cffunction name="get">
    <cfinclude template="get_function_contents" />
</cffunction>
```

... but that's the only way that mixins will work with Taffy. Sorry! I wish I could do more...
