### ISSUE TITLE
Dashboard - Request Body bug with multiple put,post, patch verbs

### ISSUE THREAD

**Issue by tvanderlois** [atuttle/Taffy#262]
Noticed a bug where the dashboard "Request Body" is blank for endpoints with multiple update verbs (put, post, patch). Did a little investigating and found a fix in line 343 of dashboard.cfm

```
taffy.resources['#local.resourceHTTPID#'] = taffy.resources['#local.currentResource.beanName#'] || {};
```

should be (I think as it does fix the issue, but didn't do further testing) 

```
taffy.resources['#local.resourceHTTPID#'] = taffy.resources['#local.resourceHTTPID#'] || {};
```

**Comment by atuttle** [comment]
Thanks for the report!
