### ISSUE TITLE
Dashboard documentation enhancement suggestion - only include verb methods

### ISSUE THREAD

**Issue by tvanderlois** [atuttle/Taffy#264]
Only include action verbs (get, post, put, pull, patch, delete) methods in the documentation. Several of my resource cfcs have helper methods that show up in the documentation. Or even better a checkbox to include helper methods?

**Comment by atuttle** [comment]
Not sure if this will fix it, but try making them private?

**Comment by tvanderlois** [comment]
Actually the latest version does only include verbs... didn't even realize. Well done.

**Comment by tvanderlois** [comment]
Okay - I'm trying to be atuttle quick with my replies... the dashboard no longer displays the non-verb methods which is great; however the specific documentation page does include the the non-verb methods. Haven't had the need to share documentation yet, but the documentation page would be a good starting point if the helper methods were excluded. Thanks

**Comment by atuttle** [comment]
:)
