### ISSUE TITLE
Error in dashboard when a duplicate URI pattern is found

### ISSUE THREAD

**Issue by admentus** [atuttle/Taffy#266]
The Taffy 3.0 release code in the dashboard for rendering alerts breaks when an duplicate URI pattern is found.

This line of code is on line 180 in /dashboard/dashboard.cfm:

    <cfset local.errorCode = local.exceptionHasErrorCode and local.err.Exception.ErrorCode>

When evaluated with a duplicate URL pattern exception, this looks like:

    <cfset local.errorCode = TRUE and 'taffy.resources.DuplicateUriPattern'>

Obviously an error is thrown when trying to perform a boolean operation on the error code string.

**Comment by atuttle** [comment]
Nice find, thanks! Will get that addressed momentarily.

**Comment by atuttle** [comment]
The fix is available in the current master branch download. No official release for it yet, but 3.1 should be out in the next few weeks.
