### ISSUE TITLE
Why not working on tomcat 8

### ISSUE THREAD

**Issue by actsone** [atuttle/Taffy#283]
Hello,

I install taffy 3.0.2 in tomcat 8, but not working and error happened. (_taffy key not founded...)
But I install taffy 2.2.6 in tomcat 8, it is working.

Can I solve it?

**Comment by atuttle** [comment]
Seems likely that this is related to #284 -- can I assume we can close this one?

**Comment by actsone** [comment]
No, this issue is another issue.
taffy 3.0.2 not working on tomcat 8 (error happened.)

- Windows 8 / tomcat 8 : not working
- windows 2003 server / tomcat 8 : not working.

**Comment by atuttle** [comment]
Are you deploying Adobe CF (which version?) on Tomcat 8? Or Lucee? Railo?

**Comment by actsone** [comment]
Lucee 4.5.1.022 and 4.5.2.000 try it.(maybe railo version also same)

**Comment by atuttle** [comment]
It looks like this is a Lucee bug.

It looks like Lucee just doesn't implement the `coldfusion.server.ServiceFactory` class right now. [The offending line](https://github.com/atuttle/Taffy/blob/master/core/api.cfc#L937) was added back [in April](https://github.com/atuttle/Taffy/pull/268) to detect a `/resources` mapping to know it was safe to use.

After I have some more time to dig into this I may be filing a bug with Lucee to get this addressed -- if you want you could take it over to them and see what they have to say about it.

**Comment by atuttle** [comment]
This has been resolved by #290
