### ISSUE TITLE
New metadata attribute taffy:invisible at component/method level to hide them from dashboard + docs

### ISSUE THREAD

**Issue by atuttle** [atuttle/Taffy#288]

**Comment by phipps73** [comment]
What if we needed to show the component/method in the dashboard but hide it from the docs or vice versa? Would separate attributes be more flexible? i.e.

taffy:dashboard
and
taffy:docs

Just an idea

**Comment by atuttle** [comment]
Instead of separate attributes, I think it would be better to have `taffy:invisible="[dashboard|docs|true]"` where true ~= "all"

**Comment by phipps73** [comment]
That makes far more sense!
