### ISSUE TITLE
Taffy URLs with params that contain '/' and/or space don't work right

### ISSUE THREAD

**Issue by tomchiverton** [atuttle/Taffy#292]
With the following simple resource

```
component extends="AbstractResource" taffy_uri="/type/{type:.*}" {
    function get( string type ){
writeLog("type #arguments.type#");
        return noData();
    }
}
```

on Lucee 4.1.x, arguments.type is correct for URLs like '/rest/type/foo/bar', but for URLs like '/rest/type/some thing else' it fails to get the whole string, regardless of encoding (%20, &nbsp;)

Mailing list discussion : https://groups.google.com/forum/#!topic/taffy-users/eEJHk_VKpxU

**Comment by atuttle** [comment]
I'm inclined to believe this is a Lucee bug (or some other part of your stack conflicting? e.g. Tomcat)

I made some small modifications to your repro case:

```
component extends="taffy.core.resource" taffy_uri="/type/{type:.*}" {
    function get( string type ){
        return rep(arguments);
    }
}
```

And when I call it from my dashboard with a type value of `foo/bar` I get this response:

![image](https://cloud.githubusercontent.com/assets/46990/9658165/3ec634f0-5215-11e5-93db-339a3b9d1803.png)

**Comment by atuttle** [comment]
Testing with `foo bar` works just as well, too.
