### ISSUE TITLE
Dashboard issues

### ISSUE THREAD

**Issue by KrunchMuffin** [atuttle/Taffy#293]
dashboard mentions that I am using the default reload password with a link, that link goes here http://docs.taffy.io/3.0.2/#reloadKey
Same with all the ? icons on the config button modal.

**Comment by atuttle** [comment]
Yeah, this is a sort of known issue and an incompatibility between how those links are generated and how the docs are handled. The links use the current Taffy version, but the docs don't always need to be copied, especially if the new version is just for bug fixes (e.g. nothing about the docs would change).

I'll think on it and see if there's any change I can make in the docs code to automatically redirect to the most recent docs for the specified major/minor version.

**Comment by atuttle** [comment]
Ok, it's not the most elegant solution but I've got a redirect in place that should achieve the desired result with our new static docs hosting.
