### ISSUE TITLE
Multiple Taffy, same server

### ISSUE THREAD

**Issue by KrunchMuffin** [atuttle/Taffy#296]
So I have Stage and Prod on the same server, not by choice, and I noticed that when it is called on Stage, it calls core on Prod.

    RAW_TRACE at     cfleads2ecfc1731713213$funcPOST.runFunction(D:\websites\xxxxx_stage\taffy\resources\leads.cfc:71)
    TEMPLATE	D:\websites\xxxxx_stage\taffy\resources\leads.cfc

    RAW_TRACE at cfapi2ecfc169888099$funcONREQUEST.runFunction(D:\websites\xxxxx\taffy\core\api.cfc:318)
    TEMPLATE	D:\websites\xxxxx\taffy\core\api.cfc`

They both have different application names. What do I need to do to make these separate?

**Comment by ryanguill** [comment]
Are you using a mapping in your coldfusion administrator for taffy?

**Comment by KrunchMuffin** [comment]
yes, there is one setup.

**Comment by ryanguill** [comment]
Then /taffy will always use that one. You will need to use application specific mappings set up in your application.cfc

**Comment by KrunchMuffin** [comment]
of course, makes sense. Working on a saturday..pfff.
