### ISSUE TITLE
Mappings not working?

### ISSUE THREAD

**Issue by KrunchMuffin** [atuttle/Taffy#297]
So, in CF admin there is a mapping of / pointing to a dir that is another site that has nothing to do with my sites. PITA. So I have to create one in all my apps that point to the dir of the current app. It works, except in Taffy.
I have this set up in Taffy app.cfc `<cfset this.mappings["/"] = "D:\websites\xxxx_stage">` but what I get back when I do `<cfdump var="#expandpath("/")#" abort>` is `D:/websites/saftey-cart/cart/ccupdateAuthNet/` which is the mapping in cf admin for /.

Anyone have a clue as to why that would be the case?

**Comment by atuttle** [comment]
I can't think of any reason Taffy would affect this. :frowning:
