### ISSUE TITLE
URL ReWrite for IIS7, CF9, Win2008 not working

### ISSUE THREAD

**Issue by CherylSue** [atuttle/Taffy#304]
Reviewed this post https://github.com/atuttle/Taffy/issues/250 but neither solution is working.

Setup using default install with a global mapping to taffy.  copied the api folder with the examples for cfartgallery. 

When I clear the site of url rewrite and use the index.cfm it works fine returning all info for Aiden Donolan.

http://mydomainname.com/api/index.cfm/artist/1

When I add web.config back I get 404.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="api" stopProcessing="true">
                    <match url="^api/(.*)$" ignoreCase="false" />
                    <action type="Rewrite" url="api/index.cfm?endpoint=/{R:0}" appendQueryString="true" />
                </rule>
            </rules>
        </rewrite>
        <httpErrors existingResponse="PassThrough" />
    </system.webServer>
</configuration>
```

When I use the OP regex it still doesn't work.

```xml
<match url="(.*)/(.*)$" ignoreCase="false" />
```

http://mydomainname.com/api/artist/1

Based on web.config In IIS there is one Edit Inbound Rule.
Name: api
Match URL-
Requested URL: Matches the Pattern
Using: Regular Expressions
Pattern: ^api/(.*)$
Action -
Action type: Rewrite
Action Properties -
Rewrite URL:
api/index.cfm?endpoint=/{R:0}
Append query string: checked
Stop processing of subsequent rules: checked

Click Test pattern -
Input data to test:  api/artist/1
Test Results: The input URL path matches the pattern.
Capture Groups:
Back Reference: {R:0} Value: api/artist/1
Back Reference: {R:1} Value: artist/1

The rule from the Wiki was using {R:0} but I needed to change it to {R:1} in order to work.

So users may need to check in order to use the correct reference.

Kudos to Adam for making this feature possible in CF9.  It will open many possibilties!

**Comment by atuttle** [comment]
Sorry that you're having trouble. Unfortunately I don't have the bandwidth to help debug url rewrite issues right now. You may find more help in the CFML slack, though: http://cfml-slack.herokuapp.com
