### ISSUE TITLE
Headers regression from #279

### ISSUE THREAD

**Issue by atuttle** [atuttle/Taffy#323]
#279 introduced OnTaffyRequestEnd and attempts to add headers (for metrics) after content has been added to the output. If the content is sufficiently large, CF will automatically flush the buffer, resulting in an exception when the we attempt to add the header.

@donwalter Any chance you want to tackle this? 😄 

Ideally we'd still get the metrics, so the serialization/etc would need to be called first... but as written the logic isn't friendly to that idea. Either the logic will need to be rewritten to save output to a variable for outputting as the last thing, or OTRE call(s) would need to be injected in a few places as appropriate. Preferably the former, I think.

**Comment by donwalter** [comment]
D'oh! I'm slammed right now with stuff, but if nobody else has fixed it by the time my schedule frees up, I'll take a look.

**Comment by donwalter** [comment]
Changed outputs to set variables, and then output after all headers have been sent. Appears to have resolved this issue. Pull request sent. Let me know if you see anything that needs changed. Sorry it took so long

**Comment by atuttle** [comment]
Thanks!
