### ISSUE TITLE
Taffy dashboard & SPDY problem

### ISSUE THREAD

**Issue by jerryhopper** [atuttle/Taffy#324]
The taffy dashboard seems have a glitch when proxied thru cloudflare.
the https requests have lowercase headers, which breaks taffy's dashboard when testing an endpoint in it.
im running taffy on lucee 4.5/tomcat

Live example of the issue :  http://cfapi.botnyx.com/  https://cfapi.botnyx.com/ 
try call the test endpoint.

**Comment by jerryhopper** [comment]
quickfix:   dashboard.js line 136  change header content type to lowercase.

if (headers['content-type'].indexOf('application/json') > -1 || headers['content-type'].indexOf('text/json') > -1  ){

Line 234 :  convert headers to lowercase.
var chunks = h.toLowerCase().split('\n');

**Comment by atuttle** [comment]
Thanks for the bug report and the notes on how to fix it. Available in the bleeding-edge-release (download the master branch), and will be included in the next tagged release.
