### ISSUE TITLE
Internal Factory should call constructors init()

### ISSUE THREAD

**Issue by adeleusiere** [atuttle/Taffy#325]
When using the internal bean Factory, the constructor (init() method) of any CFC should be called.

In instance line 26 of factory.cfc:
`b = createObject('component', this.transients[arguments.beanName]).init();`
and line 84:
`<cfset local.objBean = createObject("component", local.beanPath).init() />`

A default constructor must be added consequently to baseSerializer.cfc, baseDeserializer.cfc and resource.cfc:

```
<cffunction name="init" access="public" output="false" hint="The default constructor.">
    <cfreturn this />
</cffunction>

```

**Comment by atuttle** [comment]
Hm, I'm not thrilled about requiring every CFC in a Taffy API to have an init method; though I can see why you would want it to be called if it existed. Any reason not to just check for existence and call it if it exists?

**Comment by atuttle** [comment]
I guess the `baseSerializer` and `taffy.core.resource` base classes could implement it and you could override as you see fit. That wouldn't hurt anything.

But that doesn't cover everything you might put into your resources folder, so yeah, I'm sticking with my gut instinct (until convinced otherwise)... we should check for existence and then call it if it's there.

**Comment by adeleusiere** [comment]
Hi Adam!
Well, I've missed your reply... sorry for that...

Yes, you're right, I didn't realize that this approach would enforce any object not extending the Taffy base ones to implement an init method... so, yes, testing the existence of the init() method would be the right angle...

It would be also possible to catch the exception and basically ignore it...

**Comment by atuttle** [comment]
Question: Are you assuming that any dependencies listed as arguments would be passed in? This would add significant complexity to Taffy's factory and only duplicate an existing solution (using properties for DI).

**Comment by adeleusiere** [comment]
I was expecting to just have a constructor to init some variables. It could be enough for a simple factory.

But I did check in DI/1 quickly, the arguments names of init() are evaluated and injected. Well again, you're right, because in the constructor the dependencies are not yet injected.

So, there are two points if I understand well:
1. do the injection prior calling the constructor
2. evaluate the arguments name of the init() method

http://framework-one.github.io/documentation/using-di-one.html
`// usermanager - managers/user.cfc or usermanager.cfc component accessors=true {

    property roleService; // autowire services/role.cfc

    function setLoggingService( loggingService ) { // autowire services/logging.cfc
        variables.logger = loggingService.getLogger( "user" );
    }

    function init( userdao ) { // autowire daos/user.cfc
        variables.userdao = userdao;
        return this;
    }
}`

**Comment by atuttle** [comment]
So here's the thing. The Taffy factory doesn't need to have every feature that DI/1 has. If you want those features you're welcome to use DI/1 with Taffy, and I even do that in some cases myself! :)

I'm not opposed to having the Taffy factory call the init method if it's there, but I don't think we should go farther than that.

**Comment by atuttle** [comment]
As a final thought, while the intentions here were great and it was lovely gaming out the idea with you, I think we agree that if you want a sophisticated factory, you're better off using DI/1 which integrates with Taffy quite well. Better to not reinvent the wheel. :)
