### ISSUE TITLE
Dashboard pre-fills wrong data type for structure fields

### ISSUE THREAD

**Issue by atuttle** [atuttle/Taffy#326]
For, e.g. a POST request, the dashboard attempts to pre-fill the top-level function arguments as body parameters. It does this correctly for arrays, but if your argument type is a structure it is incorrectly pre-filled as if it were a string.

Given:

``` js
function post( required struct bio, required array widgets ) {}
```

The dashboard should pre-fill the body as:

``` js
{
   "bio": {},
   "widgets": []
}
```

But instead it is pre-filling the body as:

``` js
{
   "bio": "",
   "widgets": []
}
```

The solution will lie somewhere around here: https://github.com/atuttle/Taffy/blob/master/dashboard/dash.js#L31-L33

**Comment by bmdoherty** [comment]
I cant replicate this on mac/chrome. Its filing it out correctly for me showing `{}` not `''`.

**Comment by atuttle** [comment]
@bmdoherty Odd, that's where it's happening for me. Are you using the latest bleeding edge release? (Download of the master branch = BER; there are things in there that are not included in tagged releases yet.)

**Comment by bmdoherty** [comment]
@atuttle yes i think so, just cloned from master, will double check and have a look tomorrow

**Comment by bmdoherty** [comment]
taffy `commit f9a3457b396a7eb0b85accec6f540591d6cd246b` 
chrome `Version 53.0.2785.101 (64-bit)`

@atuttle  not sure why i am not seeing it

![screen shot 2016-09-13 at 18 58 21](https://cloud.githubusercontent.com/assets/1644770/18485275/1f39dc7a-79e4-11e6-9381-e73bbe56f23e.png)

**Comment by ajlemke** [comment]
@atuttle  
I am seeing the same results as @bmdoherty.

![image](https://user-images.githubusercontent.com/2236692/35935336-cc05734c-0c05-11e8-93a6-2585fe0b2a1a.png)

```cfm
component  extends="taffy.core.resource" taffy_uri="/test/" {
	public struct function post(required struct foo, required array bar) {}
}
```

Chrome Version 63.0.3239.132 (Official Build) (64-bit)
I am on Windows 10 if that matters.

**Comment by atuttle** [comment]
Well then I guess I was wrong. :)
