### ISSUE TITLE
Have `withStatus()` lookup the proper `statusText` based on the `statusCode`

### ISSUE THREAD

**Issue by Panman8201** [atuttle/Taffy#329]
I'll take a crack at this enhancement, just wanted to create an issue to gather any specifics that might be needed before I get started.

If there are no objections, I'll make the list of status code text from the MDN article: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by atuttle** [comment]
No objection here. Seems like there may be some missing but it's a good place to start. I usually use http://httpstatus.es as a reference but they appear to be down at the moment.

**Comment by Panman8201** [comment]
Alright, working on this now. That site is back online and here are the missing ones that I noticed:

* 102 = Processing
* 207 = Multi-Status
* 208 = Already Reported
* 226 = IM Used
* 418 = I'm a teapot
* 422 = Unprocessable Entity
* 423 = Locked
* 424 = Failed Dependency
* 444 = Connection Closed Without Response
* 499 = Client Closed Request
* 507 = Insufficient Storage
* 508 = Loop Detected
* 510 = Not Extended
* 599 = Network Connect Timeout Error

So would you like me to include the entire list or a select few (probably end up being most anyway...)?
