### ISSUE TITLE
Image Uploading

### ISSUE THREAD

**Issue by MYWSteve** [atuttle/Taffy#343]
Is it possible to allow an open-ended number of images (up to 99) to be passed in a single post? Are there any examples of this?

**Comment by atuttle** [comment]
I've never tried. I think the way that Adobe ColdFusion (no clue for Lucee) handles file uploads requires you to know the form field names, and that doesn't really jive well with the approach Taffy takes.

Personally I would have my API create some sort of bucket or entity that each image would be attaching itself to, and have the client submit one image per POST to be added to that entity. There's no reason you couldn't run these in parallel, especially if your API runs on a distributed cluster: It would even be faster that way.

**Comment by MYWSteve** [comment]
Hi Adam, thanks for getting back to me. Everything I've seen leads me to
the same conclusion.

Steve Madsen
------------------------------
Programmer Analyst | Murals Your Way <http://www.muralsyourway.com/>
E: steve@muralsyourway.com
P: 952.938.1300 ext.760 | F: 800.328.9349
M: 717 5th Street S Hopkins, MN 55343
------------------------------
Facebook <https://www.facebook.com/MuralsYourWay> | Pinterest
<http://www.pinterest.com/muralsyourway/> | Twitter
<https://twitter.com/MuralsYourWay> | Houzz
<http://www.houzz.com/pro/muralsyourway/murals-your-way> | Instagram
<http://instagram.com/muralsyourway>

<http://www.muralsyourway.com/>
