### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by atuttle** [atuttle/Taffy#349]
Thanks to @pfreitag we now have Travis-CI setup to run our unit tests!

Unfortunately, [some of them are failing](https://travis-ci.org/atuttle/Taffy/).

It would be rad if you wanted to contribute some changes (even if it's fixing tests that are busted rather than code that they think they're testing...) to help us move toward 100% passing.

Another thought would be converting from MxUnit tests that run via TestBox compatibility to actual TestBox tests.

**Comment by pfreitag** [comment]
FYI to run the tests locally install commandbox then do the following:

```
git clone https://github.com/atuttle/Taffy.git .
box install
box server start
```

At that point you will have a Lucee 4.5 server running on some random port, you can then go to the URI: `/tests/tests/run.cfm` to see the test output. If you want to test on a different CFML engine just switch the line `box server start` to `box server start cfengine=adobe@2016` for example.

**Comment by pfreitag** [comment]
After the fix I just made there are now only 9 failing tests out of the 79 tests. 4 are failures and 5 are exceptions.

**Comment by atuttle** [comment]
Looks like there are no more failing tests. Time to close this ticket. ❤️ all of the contributions to make this happen!
