### ISSUE TITLE
un-vared variable

### ISSUE THREAD

**Issue by robertdmunn** [atuttle/Taffy#353]
In /bonus/LogToBugLogHQ.cfc, line 44:

    <cfset reqHeaders = getHTTPRequestData().headers />

should be:

    <cfset var reqHeaders = getHTTPRequestData().headers />

**Comment by atuttle** [comment]
@robertdmunn thanks for the bug report! As this is such a simple fix I'm adding labels and leaving this as-is in hopes it will encourage someone new to OSS to get involved and help fix it. :)

**Comment by robertdmunn** [comment]
Adam, I'll probably fix it in the next day or two. Just started working on
a site with a Taffy API ...

**Comment by atuttle** [comment]
Great. If you'd like any advice on getting started with pull requests (no idea what your experience level is), I have some here: http://adamtuttle.codes/your-first-github-pull-request/
