### ISSUE TITLE
noData() sends invalid response

### ISSUE THREAD

**Issue by tsongas** [atuttle/Taffy#365]
Calling `return noData()` still sends an `application/json` content type header with the response, even though the body does not contain valid JSON. This causes a client that expects valid JSON to choke on the response. I am therefore unable to use the noData() function, and have to do this instead `return representationOf({})` so that an empty response is still valid JSON. Maybe noData() should either send a valid empty JSON object, or the `application/json` header should not be sent.

**Comment by atuttle** [comment]
Interesting perspective, thanks for sharing. I've had the same problem and didn't think it was the header causing it but rather that the ajax library I was using as my REST client was not handling the response appropriately.

I suppose it does make some sense that when the response body is empty the Content-Type header should be something else. Any suggestion about what it should be? Perhaps `text/plain` ?

**Comment by ryanguill** [comment]
Would the right answer be to omit the content-type header entirely? or is that required?

**Comment by tsongas** [comment]
I'm not sure about technical requirements but to me it's common sense that if there's no content, there should be no content-type header.

**Comment by tsongas** [comment]
It might help to see how Frisby decides whether to automatically parse JSON https://github.com/vlucas/frisby/pull/412/files.

**Comment by adeleusiere** [comment]
I was also wondering this (small) issue.

It is interesting how Frisby is dealing with this.
By default, noData() should also set the HTTP Status code to 204 (No Content, see https://httpstatuses.com/204). And I agree it makes sense to omit the Content-Type header.

**Comment by atuttle** [comment]
All sounds good to me. PR's welcome. :)

And there is a process for docs PR's too. ;)

**Comment by adeleusiere** [comment]
Well, I think I have time for this one, I'll do it, will be my xmas gift ;-)

**Comment by atuttle** [comment]
@adeleusiere can't assign to you without adding you as a committer, but we can let this comment stand in for assignment. Please consider it yours unless otherwise stated. :)

**Comment by adeleusiere** [comment]
Well... I made the change to have a 204 HTTP status code. But to omit the Content-Type header, it's not a piece of cake. I don't find a solution, even by looking at the underlying Tomcat ResponseFacade (https://tomcat.apache.org/tomcat-8.0-doc/api/index.html).

`<cfscript>
rs = getPageContext().getResponse();
dump(rs);
</cfscript>`

Is someone has an idea how to force that?

Otherwise, I would propose to set the Content-Type to `text/plain` to avoid misinterpretation of empty JSON string.
