### ISSUE TITLE
Bootstrap 4.1

### ISSUE THREAD

**Issue by jmohler1970** [atuttle/Taffy#373]
The dashboard UI should be powered by Bootstrap 4.1.

**Comment by atuttle** [comment]
Why should I undertake a bunch of work to update a bunch of stuff that's working just fine? What benefit is there other than "keeping up"?

**Comment by atuttle** [comment]
To be clear, I'm not opposed to updating to a more recent version of Bootstrap (if someone else wants to do the work)... there's just not a pressing need for it.

If (anyone) intends to tackle this, please post a comment here so that others can be aware and nobody else wastes their time working on it too.

**Comment by jmohler1970** [comment]
I am seeing a couple of choices

1. Do nothing (always a popular choice)
2. Do Bootstrap 4.1.2 
3. Do Bootstrap 4.2 and remove jQuery. I don't know the role of jQuery in this project off the top of my head
4. Do Bulma instead. It doesn't use jQuery or any other JS library

**Comment by atuttle** [comment]
This is the first time I've ever heard of Bulma, so I'm not likely to accept it as something that I'll have to maintain into the future... Maybe if it starts taking over the internet and I end up learning it, but not for now.

Off the top of my head, jQuery serves these purposes in Taffy:
- making Ajax requests from the dashboard (likely many people out there without `fetch` support in their browsers)
- Used by bootstrap / our dashboard code for accordions and other dynamic visual effects.

**Comment by jmohler1970** [comment]
I see that the CSS and JS are `<cfincluded>` . In particular dashboard.cfm has

```
	<style>
		<cfinclude template="dash.css" />
		<cfinclude template="highlight-github.min.css" />
	</style>
```

And

```
	<script type="text/javascript">
		<cfinclude template="jquery.min.js" />
		<cfinclude template="bootstrap.min.js" />
		<cfinclude template="highlight.min.js" />
		<cfinclude template="dash.js" />
```

I am not familiar with this approach. How is this better than using a CDN or src?

**Comment by jmohler1970** [comment]
After careful consideration, I have decided

That is really hard. I don't have enough expertise in CSS floats to pull this off in a reasonable amount of time.
