### ISSUE TITLE
Etag implementation doesn't follow specification

### ISSUE THREAD

**Issue by timmixell** [atuttle/Taffy#395]
Per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag , the value of the Etag should be placed in double quotes.

It does not appear that Taffy currently renders the Etag values within double quotes, and this is causing Cloudflare to remove the Etag from the response: https://support.cloudflare.com/hc/en-us/articles/218505467-Does-CloudFlare-support-ETag-headers-

I *believe* that because the Etag is generated from a hash of the actual payload content, that it is safe to assume strong Etags.

**Comment by atuttle** [comment]
Makes sense to me. Further, I don't think adding quotes is going to break anything, so this can be included in a minor version release.

**Comment by pfreitag** [comment]
Wow, I never realized etags were supposed to be in double quotes, that's not typical for a header value. The quotes are then used to imply different connotations about their strength.  The more you learn about the web the more quirky you realize it is and has always been.
