### ISSUE TITLE
Default branch is "master" instead of "main"

### ISSUE THREAD

**Issue by drew-smithies** [atuttle/Taffy#412]
If you use `git://github.com/atuttle/Taffy.git` in a box.json file it gives an error saying 

      Error cloning git repository
      org.eclipse.jgit.api.errors.RefNotFoundException: Ref master cannot be resolved 

Specifying the `main` branch fixes the issue
    
     git://github.com/atuttle/Taffy.git#main

Was this intentional? I would suggest setting the default branch to `main`.

**Comment by atuttle** [comment]
Pretty sure this has been resolved.
